# For more information see https://sphinx-theme.scylladb.com/stable/deployment/production.html#available-workflows

name: "Docs-CI"
env:
  FLAG: ${{ github.repository == 'scylladb/scylla-enterprise' && 'enterprise' || 'opensource' }}
  PR_NUMBER: ${{ github.event.pull_request.number }}
  AWS_EC2_METADATA_DISABLED: true

on:
  pull_request:
    paths:
      - "docs/**"
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.7

      - name: Set up env
        run: make -C docs FLAG="${{ env.FLAG }}" setupenv

      - name: Build docs
        run: make -C docs FLAG="${{ env.FLAG }}" test

      - name: Publish preview docs
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DOCS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DOCS_AWS_SECRET_ACCESS_KEY }}
        run: aws s3 sync docs/_build/dirhtml "s3://dev-docs.scylladb.com/$GITHUB_REPOSITORY/$PR_NUMBER" --delete

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v38.1.3
        with:
          files: docs/**/*.{md,rst}

      - name: Generate direct URLs and comment on the pull request
        run: |
          for FILE in ${{ steps.changed-files.outputs.all_changed_files }}; do
            URL_PATH=$(echo "$FILE" | sed -E 's/^docs\/(source\/)?(.+)\.(md|rst)$/\2/' | sed 's#/#/#g')
            DIRECT_URL="http://dev-docs.scylladb.com/$GITHUB_REPOSITORY/${PR_NUMBER}/$URL_PATH"
            DIRECT_URLS="$DIRECT_URLS\n- $DIRECT_URL"
          done

          API_COMMENT_URL="https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$PR_NUMBER/comments"
          PREVIEW_PAGE_URL="http://dev-docs.scylladb.com/$GITHUB_REPOSITORY/${PR_NUMBER}"
          COMMENT_BODY="Documentation preview of this pull request is available [here]($PREVIEW_PAGE_URL).\n\n"
          COMMENT_BODY+="**Changed Files:**$DIRECT_URLS"
          COMMENT_BODY+="\n\n**Note:** Once the pull request is merged or closed, the preview will be automatically deleted."
          curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -d "{\"body\":\"$COMMENT_BODY\"}" "$API_COMMENT_URL"
